### ISSUE TITLE
Make opcache values configurable

### ISSUE THREAD

**Issue by arhue** [StephenMiracle/frankenwp#24]
Would be nice if the opcache values were configurable. I'm looking to run WP on a low end server and 128mb is too much memory to allocate to opcache for me.

[    echo 'opcache.memory_consumption=128'; \](https://github.com/StephenMiracle/frankenwp/blob/fd4bda4476d36e351059f8e05a4349645b97ff45/Dockerfile#L88)

**Comment by StephenMiracle** [comment]
Ya. This makes sense. Will get it updated.

**Comment by arhue** [comment]
I managed to solve this with docker compose. You would need a newer version of Docker compose. Config would look something like this.

```
services:
  wordpress:
  ...
  configs: 
    - source: php_ini
      target: /dest/to/php.ini
configs:
  php_ini:
    content: |
       insert-php-ini-content-here-line1
       insert-php-ini-content-here-line2

```
